language: node_js
sudo: false
node_js:
- "5.0"
- "4.2"
- "4.1"
- "4.0"
before_install: "npm install npm@'>=3.3.6' -g"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Send coverage data to Coveralls
after_script: "cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
