language: node_js
sudo: false
node_js:
- "4.1"
- "4.0"
before_install: "npm install npm@'>=3.3.6' -g"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
